; this is an example file for ini-parse.h

; example of a key/value pair
bar = baz

; another example of a key/value pair
foo = bar

; section names cannot include [ or ]
[section]
this-is-a-null    = null
this-is-also-null = null
string-no-quotes  = this is a string without quotes

; strings can be quoted in order to include surrounding whitespace
string-quotes     = "   This is a string with quotes"
number            = 3.141500
boolean           = true
bar               = baz
foo               = bar
