# section-less
section_less_value = 4

[section]
some_string        = this is a string! yippie!
some_string_quote  = "hello, world!"
some_boolean       = true
some_other_boolean = false
some_integer       = 23
some_integer_hex   = 0x2F
some_integer_max   = 0xffffffff
some_float         = 1.2

# back to empty section
[]

another_value = 7

